name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: macos-latest
            target: "x86_64-apple-darwin"
            build: |
              npx node-gyp rebuild
              strip -x *.node
            name: "darwin-x64"
          - host: windows-latest
            build: npx node-gyp rebuild --arch=ia32
            target: "i686-pc-windows-msvc"
            name: "win32-ia32"

    name: stable - ${{ matrix.settings.target }} - node@16
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3

      - name: "Build"
        run: make
        shell: bash
