name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: macos-latest
            target: "x86_64-apple-darwin"
            build: |
              npx node-gyp build
              strip -x *.node
          - host: windows-latest
            build: npx node-gyp build
            target: "i686-pc-windows-msvc"

    name: stable - ${{ matrix.settings.target }} - node@16
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: yarn

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-build-${{ matrix.settings.target }}-node@16

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: "*.node"
          if-no-files-found: error

  test-bindings:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: "x86_64-apple-darwin"
          - host: windows-latest
            target: "x86_64-pc-windows-msvc"
        node: ["14", "16", "18"]
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: artifacts

      - name: Move artifacts
        run: yarn artifacts
        shell: bash

      - name: Test bindings
        run: |
          yarn test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - test-bindings
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: yarn

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-ubuntu-latest-publish-${{ hashFiles('yarn.lock') }}

      - name: "Install dependencies"
        run: yarn install --immutable --mode=skip-build

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts
        shell: bash

      - name: Move artifacts
        run: yarn artifacts

      - name: Publish
        if: "startsWith(github.event.head_commit.message, 'chore(release): publish')"
        run: |
          yarn publish from-package --no-verify-access --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
