name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: macos-latest
            target: "x86_64-apple-darwin"
            build: |
              npx node-gyp rebuild
              strip -x *.node
            name: "darwin-x64"
          - host: windows-latest
            build: npx node-gyp rebuild --arch=ia32
            target: "i686-pc-windows-msvc"
            name: "win32-ia32"

    name: stable - ${{ matrix.settings.target }} - node@16
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: npm

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-build-${{ matrix.settings.target }}-node@16

      - name: "Install dependencies"
        run: npm ci --ignore-scripts

      - name: "Build"
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.settings.name }}
          path: "*.node"
          if-no-files-found: error

  test-bindings:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: "x86_64-apple-darwin"
          - host: windows-latest
            target: "i686-pc-windows-msvc"
        node: ["16"]
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: .

      - name: Test bindings
        run: |
          npm test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - test-bindings
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@xltan"

      - name: "Install dependencies"
        run: npm ci --ignore-scripts

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: npm

      - name: Publish
        run: |
          npm publish ./npm/win32-ia32
          npm publish ./npm/darwin-x64
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
